// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA93b533Jrww2HM2NzpAuivA9a3iqWpkgI',
    appId: '1:186161700348:web:d3a07a9fe61ff1da83e679',
    messagingSenderId: '186161700348',
    projectId: 'multilanguage-b66b6',
    authDomain: 'multilanguage-b66b6.firebaseapp.com',
    storageBucket: 'multilanguage-b66b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVdaXYP7l-GBeAOCVN7LZa4UpiHtgGO44',
    appId: '1:186161700348:android:64f2c5349664052783e679',
    messagingSenderId: '186161700348',
    projectId: 'multilanguage-b66b6',
    storageBucket: 'multilanguage-b66b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChOe9R7TIebdpOFIFW1zeb-65okvaRLjs',
    appId: '1:186161700348:ios:5c9d978edf59406583e679',
    messagingSenderId: '186161700348',
    projectId: 'multilanguage-b66b6',
    storageBucket: 'multilanguage-b66b6.firebasestorage.app',
    iosBundleId: 'com.example.se380Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChOe9R7TIebdpOFIFW1zeb-65okvaRLjs',
    appId: '1:186161700348:ios:5c9d978edf59406583e679',
    messagingSenderId: '186161700348',
    projectId: 'multilanguage-b66b6',
    storageBucket: 'multilanguage-b66b6.firebasestorage.app',
    iosBundleId: 'com.example.se380Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA93b533Jrww2HM2NzpAuivA9a3iqWpkgI',
    appId: '1:186161700348:web:ab2839a9fb0aacef83e679',
    messagingSenderId: '186161700348',
    projectId: 'multilanguage-b66b6',
    authDomain: 'multilanguage-b66b6.firebaseapp.com',
    storageBucket: 'multilanguage-b66b6.firebasestorage.app',
  );

}